name: ESLint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # You can adjust the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run ESLint module testing
        run: npm run lint # Replace with your ESLint command
